# Generated by Django 4.2 on 2023-04-17 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webi', '0002_rename_post_lajmet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lajmet',
            options={'verbose_name_plural': 'Lajmets'},
        ),
    ]
