# Generated by Django 4.2 on 2023-04-17 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webi', '0005_lajmet_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='projektet',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='shpallje',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='images/'),
        ),
    ]
