# Generated by Django 4.2 on 2023-04-18 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webi', '0006_projektet_image_shpallje_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lajmet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lajmet_images'),
        ),
    ]
