# Generated by Django 4.2 on 2023-04-18 01:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webi', '0014_alter_lajmet_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projektet',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projektet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projektet_images/'),
        ),
        migrations.AlterField(
            model_name='shpallje',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shpallje',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shpallje_images/'),
        ),
    ]
