# Generated by Django 4.2 on 2023-04-18 11:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webi', '0015_alter_projektet_body_alter_projektet_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lajmet',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
