# Generated by Django 4.2 on 2023-04-27 14:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webi', '0016_lajmet_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='projektet',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='shpallje',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='lajmet',
            name='image',
            field=models.ImageField(blank=True, default='ambienti-cover.jpg', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='projektet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='shpallje',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
