# Generated by Django 4.2 on 2023-04-27 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webi', '0017_projektet_pub_date_shpallje_pub_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shpallje',
            name='author',
        ),
        migrations.DeleteModel(
            name='Projektet',
        ),
        migrations.DeleteModel(
            name='Shpallje',
        ),
    ]
