# Generated by Django 4.2 on 2023-04-27 14:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webi', '0019_rename_lajmet_postimet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Postimet',
            new_name='Lajmet',
        ),
    ]
