# Generated by Django 4.2 on 2023-04-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webi', '0020_rename_postimet_lajmet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='lajmet',
            name='category',
            field=models.CharField(default='lajmet', max_length=255),
        ),
    ]
