# Generated by Django 4.2 on 2023-04-27 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webi', '0021_category_lajmet_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lajmet',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webi.category'),
        ),
    ]
