# Generated by Django 4.2 on 2023-04-27 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webi', '0023_rename_category_lajmet_kategorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lajmet',
            name='kategorite',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
