# Generated by Django 4.2 on 2023-04-27 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webi', '0024_remove_lajmet_kategorite_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
