# Generated by Django 4.2 on 2023-04-27 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webi', '0026_delete_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lajmet',
            options={},
        ),
    ]
