# Generated by Django 4.2 on 2023-04-27 15:24

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webi', '0027_alter_lajmet_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lajmet',
            options={'verbose_name_plural': 'Lajmet'},
        ),
        migrations.AlterField(
            model_name='lajmet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.CreateModel(
            name='Shpallje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='shpallje_images/')),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('pub_date', models.DateField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Shpallje',
            },
        ),
        migrations.CreateModel(
            name='Projektet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projektet_images/')),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('pub_date', models.DateField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Projektet',
            },
        ),
    ]
