# Generated by Django 4.2 on 2023-04-27 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webi', '0028_alter_lajmet_options_alter_lajmet_image_shpallje_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shpallje',
            name='author',
        ),
        migrations.DeleteModel(
            name='Projektet',
        ),
        migrations.DeleteModel(
            name='Shpallje',
        ),
    ]
