# Generated by Django 4.2 on 2023-04-27 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webi', '0029_remove_shpallje_author_delete_projektet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lajmet',
            name='author',
        ),
    ]
