# Generated by Django 4.2 on 2023-05-01 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webi', '0033_document_delete_uploadedfile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name_plural': 'Materiale per shkarkim'},
        ),
    ]
